### ISSUE TITLE
bitmap functie

### ISSUE THREAD

**Issue by sebasman15** [sebasman15/SOFTONT#1]

**Comment by JorikWiegman** [comment]
#ma_15_05: 2 x 5 uur
Gedaan:
Mogelijk plaatjes af te beelden
Mogelijk locatie in te voeren

ToDo:
Fatsoenlijke functies
Evt. Flash geheugen
Kleur meegeven aan pijlen
region `ram' overflowed by 19232 bytes

**Comment by sebasman15** [comment]
alle todo's zijn behandeld
