### ISSUE TITLE
tekst functie

### ISSUE THREAD

**Issue by sebasman15** [sebasman15/SOFTONT#10]

**Comment by sebasman15** [comment]
grootte af

**Comment by JorikWiegman** [comment]
Mogelijk:
één letter (g) plaatsen. Wel met een eigen .h file en aparte functie
(Zie  letter_g_write() functie).

Bezig:
char_write(), functie zoekt naar verschillende waarden en voert write_char_VGA() aan.

char_write() zoekt naar waarden in de volgende functies:
  - determine_char() // geeft nummer (int) door ipv char
  - calc_writing_space() // in volle bytes, nodig voor write_char_VGA() (waarschijnlijk overbodig in char_write(), haha.
  - calc_char_space() // werkelijke ruimte (handig voor write_string_VGA())
  - determine_offset() // dan weet de write_char_VGA waar hij precies moet beginnen in de grote array.

write_char_VGA(). basis van letter_g_write(). Kan nog niet getest worden. eerst moeten bovenstaande functies af zijn.

ToDo:
Nog te doen in al bestaande functies:
  - determine_char(): case statement schrijven.
  - calc_writing_space(): onderzoeken hoe één waarde uit de array van 'georgia_16ptDescriptors[]' kan worden gehaald.
  - calc_char_space():  Idem dito
  - determine_offset(): Idem dito. Echter, nu moet tweede waarde worden opgevist.

write_string_VGA(): maakt gebruik van 'write_char_VGA()'. Functie houdt rekening met de waarde uit 'calc_char_space()', de daadwerkelijke grootte van het karakter, en voegt een paar lege pixels toe zodat karakters niet aan elkaar plakken. 




NOTE: Ik heb de code nog niet op GitHub gezet. De code is namelijk nog niet af. de code is te vinden op dropbox (zie mapje 'tekst_georgia16pt').
  - tekst.c
  - tekst.h
  - letter_g.h
  - georgia_16pt_normal.h
